removing homecomponent
raquel-ucl/oracc-search-front-end pull request #61
Opened 2024-03-27 11:22 UTC by acholyn

- Removed the `HomeComponent` and using search as the main page
- updated routing so search is now base

Does the breadcrumb function need to be updated?

2024-04-04 12:41 UTC, jhughes982 commented
I can't give a thorough review of your code right now unfortunately. But I spotted that you have included your `package-lock.json` file to gitignore. Unless you have a specific reason to do so, this file should generally be included in source control.

https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5

2024-04-04 16:28 UTC, tim-band requested changes
README.md has a section "Running end-to-end tests" which should be updated to show how these tests should be run.

2024-04-04 18:31 UTC, tim-band commented
Should merge in the dev branch.

2024-04-04 18:59 UTC, tim-band commented
Need to .gitignore `cypress/screenshots`

2024-04-05 09:41 UTC, acholyn commented
I tried the command for the unit tests and the window opens saying complete but also says there were no specs found. Are there no unit tests or is this broken?

2024-04-05 09:43 UTC, acholyn commented
> Should merge in the dev branch.

I'm apparently up to date - perhaps because I built this branch off development recently and then merged in the cypress stuff from longer ago

2024-04-05 15:20 UTC, tim-band commented
There are two more `/search/search-results/` in the project.

2024-04-08 16:58 UTC, tim-band approved these changes
OK all done, bar some new stuff I want to do.

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +const oraccUrl = 'https://oracc.museum.upenn.edu/search';
Needs to be http://localhost:4200/

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('.cookies').should('be.visible');
This line fails for me. Is there some setting for Cypress that means we start without cookies set?

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('.glossary').should('be.visible');
This line fails for me. I don't have any `.glossary` class on the page. Should it be there?

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('span.sux').eq(1).click();
This doesn't work, but it's not your fault. I'll try to fix it. Why is so much of this app mysteriously broken?

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('span.sux').eq(1).click();
Maybe it is your fault! It seems there's a load of `'search/search-results'` links that need to be removed. A lot of them are behind a check to see if we are in mobile mode. That suggests we should be running all these tests in mobile mode, too!

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('span.marker').first().click();
You need `trigger('mouseover')` now, not `click()`.

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('.details__popup').should('be.visible').should('have.text');
You need `#n1344` or something here to select the box. `have.text` doesn't mean what you think it does, either. Should probably test that it's invisible then becomes visible with the mouseover. Turns out it's quite hard to check for contained text if that text trails nested elements, don't know why.

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('.cookies').should('be.visible');
Ah, it's not that. James added a line in CookiesComponent that prevents the cookie banner from being shown if we're in dev mode. Should we change this to `isHidden = false;` so that we can test this functionality?

2024-04-08 16:58 UTC, tim-band commented on src/app/pages/glossary-article-source/glossary-article-source.component.ts
> -          `/search/search-results/${decodeURI(this.pathnameArray[2])}`,
I don't think this is correct. I think it's `this.pathnameArray[1]`, which means we can remove the if/else.

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('.glossary').should('be.visible');
Seems fine now.

2024-04-08 16:58 UTC, tim-band commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('span.marker').first().click();
Looks like click() is actually working.

2024-04-08 16:58 UTC, tim-band commented on src/app/pages/glossary-article-source/glossary-article-source.component.ts
> -          `/search/search-results/${decodeURI(this.pathnameArray[2])}`,
Actually, don't worry about this, I think the problem is actually much worse! Let's leave it for another PR.

2024-04-09 10:44 UTC, acholyn commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('span.sux').eq(1).click();
All of the tests pass for me, is this still an issue for you?

2024-04-09 10:49 UTC, acholyn commented on cypress/e2e/smokeTest.cy.ts
> +    cy.get('.cookies').should('be.visible');
Either that or we could include some sort of conditional for the test if we plan to change the `oraccUrl` to a published website

2024-04-10 10:58 UTC, merged